# SPDX-FileCopyrightText: 2006-2024 Knut Reinert & Freie Universität Berlin
# SPDX-FileCopyrightText: 2016-2024 Knut Reinert & MPI für molekulare Genetik
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuo pipefail {0}

jobs:
  license_check:
    name: "REUSE Compliance"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v2

  build:
    name: "Scavenger Hunt"
    needs: [license_check]
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool Versions
        run: |
          set +eu
          echo "LANG=$LANG"
          echo "##############################################################################"
          echo "LC_ALL=$LC_ALL"
          echo "##############################################################################"
          bash --version
          echo "##############################################################################"
          awk -W version
          echo "##############################################################################"
          diff --version
          echo "##############################################################################"
          comm --version
          echo "##############################################################################"
          sed --version
          echo "##############################################################################"
          sort --version
          echo "##############################################################################"
          uniq --version
          echo "##############################################################################"
          wget --version
          echo "##############################################################################"
          curl --version
          echo "##############################################################################"
          grep --version
          echo "##############################################################################"
          zip -v
          echo "##############################################################################"
          unzip -v
          echo "##############################################################################"
          jq --version

      - name: Create Scavenger Hunt
        run: ./create_scavenger_hunt.sh

      - name: Solve Scavenger Hunt
        run: ./test.sh

      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: double-zipped-start
          path: start.zip
